### ISSUE TITLE
can not install Ropper with pip on Linux

### ISSUE THREAD

**Issue by ls4cfk** [sashs/Ropper#103]
I am trying to write some script which requires ropper. (install only via pip) How can i fix this problem?

I am trying to install it on linux, tried to upgrade setuptools, install old version and followed this, only one topic, which i found: the link!

This is the error message:
```
$ pip install ropper

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting ropper
  Using cached https://files.pythonhosted.org/packages/94/b1/922dfab5083ff439ce70358c7f3e49185c54e6ea6ee2bb7cd292e63eac06/ropper-1.12.1.tar.gz
Collecting filebytes>=0.9.18 (from ropper)
  Using cached https://files.pythonhosted.org/packages/0b/3a/9fc0c62bd74583137a8bbc3c8020d6a8234b9cf8bc1e99fe929688b19093/filebytes-0.9.20.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d44HeD/filebytes/setup.py", line 3, in <module>
        from pathlib import Path
    ImportError: No module named pathlib
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-d44HeD/filebytes/
```

**Comment by sashs** [comment]
Hi. The solution would have been to install pathlib. ;) 
` ImportError: No module named pathlib`
Pathlib was used in setup.py of filebytes. But I removed this dependency a while ago, but I forgot to upload it to pypi. I've just uploaded it. So it should work now.
