### ISSUE TITLE
NoneType error for virtualprotect

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [sashs/Ropper#114]
Tried to develop a rop chain for a CTF using the virtualprotect method. However when I tried to do this. I got this error. 

P.S. Thx for the developing and improving this tool

[INFO] Load gadgets from cache
[LOAD] loading... 100%
[LOAD] removing double gadgets... 100%

[INFO] Ropchain Generator for VirtualProtect:

[INFO] eax 0x90909090
ecx old protection (writable addr)
edx 0x40 (RWE)
ebx size
esp address
ebp return address (jmp esp)
esi pointer to VirtualProtect
edi ret (rop nop)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 360, in __generateChain
    chain = self.__rs.createRopChain(generator, str(self.currentFile.arch) ,options)
  File "/usr/local/lib/python2.7/dist-packages/ropper/service.py", line 775, in createRopChain
    return generator.create(options)
  File "/usr/local/lib/python2.7/dist-packages/ropper/ropchain/arch/ropchainx86.py", line 925, in create
    address, image_base = self.__getVirtualProtectEntry()
TypeError: 'NoneType' object is not iterable

[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 62, in cmd
    func(self, text)
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 499, in __handleOptions
    self.__generateChain(options.chain)
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 377, in __generateChain
    raise e
TypeError: 'NoneType' object is not iterable

**Comment by KittyTechnoProgrammer** [comment]
I assume this means it was unable to find a pointer to virtualprotect?

**Comment by sashs** [comment]
Hey, 

the bug should be fixed. Yes, you are right. ropper could not found a virtualprotect pointer.
