### ISSUE TITLE
ValueError: ('aba885b34ffe9781f44af295bd9e6cfa6754e83fe07e628b3a0b04eae3b79f56', 'LOAD') is not in list

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [sashs/Ropper#120]
The command : 

ropper --chain="execve" --badbytes 000a0d --file ./heap0_static

The error : 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 711, in create
    chain_tmp += self._createSyscall()[0]
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 598, in _createSyscall
    raise RopChainError('Cannot build syscall gadget!')
ropper.common.error.RopChainError: Cannot build syscall gadget!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ropper/console.py", line 360, in __generateChain
    chain = self.__rs.createRopChain(generator, str(self.currentFile.arch) ,options)
  File "/usr/lib/python3/dist-packages/ropper/service.py", line 775, in createRopChain
    return generator.create(options)
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 719, in create
    chain_tmp += self._createOpcode('0f05')
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 609, in _createOpcode
    return self._printRopInstruction(gadget)
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 176, in _printRopInstruction
    toReturn = ('rop += rebase_%d(%s) # %s\n' % (self._usedBinaries.index((gadget.fileName, gadget.section)),toHex(gadget.lines[0][0],8), gadget.simpleString()))
ValueError: ('aba885b34ffe9781f44af295bd9e6cfa6754e83fe07e628b3a0b04eae3b79f56', 'LOAD') is not in list

[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 711, in create
    chain_tmp += self._createSyscall()[0]
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 598, in _createSyscall
    raise RopChainError('Cannot build syscall gadget!')
ropper.common.error.RopChainError: Cannot build syscall gadget!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ropper/console.py", line 62, in cmd
    func(self, text)
  File "/usr/lib/python3/dist-packages/ropper/console.py", line 499, in __handleOptions
    self.__generateChain(options.chain)
  File "/usr/lib/python3/dist-packages/ropper/console.py", line 377, in __generateChain
    raise e
  File "/usr/lib/python3/dist-packages/ropper/console.py", line 360, in __generateChain
    chain = self.__rs.createRopChain(generator, str(self.currentFile.arch) ,options)
  File "/usr/lib/python3/dist-packages/ropper/service.py", line 775, in createRopChain
    return generator.create(options)
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 719, in create
    chain_tmp += self._createOpcode('0f05')
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 609, in _createOpcode
    return self._printRopInstruction(gadget)
  File "/usr/lib/python3/dist-packages/ropper/ropchain/arch/ropchainx86_64.py", line 176, in _printRopInstruction
    toReturn = ('rop += rebase_%d(%s) # %s\n' % (self._usedBinaries.index((gadget.fileName, gadget.section)),toHex(gadget.lines[0][0],8), gadget.simpleString()))
ValueError: ('aba885b34ffe9781f44af295bd9e6cfa6754e83fe07e628b3a0b04eae3b79f56', 'LOAD') is not in list

**Comment by sashs** [comment]
Could you provide the binary, please?

**Comment by KittyTechnoProgrammer** [comment]
Yes, however, I would need to find my USB. I will try to have it to you tomorrow.

**Comment by KittyTechnoProgrammer** [comment]
Hey I got. School got in the way. 
[heap0_static.zip](https://github.com/sashs/Ropper/files/3980229/heap0_static.zip)

**Comment by sashs** [comment]
Hey, sorry for the very long delay
. I cannot reproduce this issue
