### ISSUE TITLE
tests fail on macOS: RuntimeError: context has already been set

### ISSUE THREAD

**Issue by stevecheckoway** [sashs/Ropper#160]
Running the test suite fails on macOS fails. This leads to the Nix package being marked as [broken](https://github.com/NixOS/nixpkgs/blob/cc6ac970d5de7ecbc130b3ecfac1c127aca67bf5/pkgs/development/python-modules/ropper/default.nix#L39).

I'm testing this on
```
[worksec:/tmp/ropper] (master*) steve% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G9323
```

If I create a venv, install capstone and filebytes, and then run `python test.py`, I get several errors as shown below. These stem from the Python multiprocessing module.

```
[worksec:/tmp/ropper] (master*) steve% python --version
Python 3.9.13
[worksec:/tmp/ropper] (master*) steve% pip install capstone filebytes
Collecting capstone
  Using cached capstone-4.0.2.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... done
Collecting filebytes
  Using cached filebytes-0.10.2.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for capstone, since package 'wheel' is not installed.
Using legacy 'setup.py install' for filebytes, since package 'wheel' is not installed.
Installing collected packages: filebytes, capstone
  Running setup.py install for filebytes ... done
  Running setup.py install for capstone ... done
Successfully installed capstone-4.0.2 filebytes-0.10.2
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/private/tmp/ropper/venv/bin/python -m pip install --upgrade pip' command.
[worksec:/tmp/ropper] (master*) steve% python test.py
.................EEE...........
======================================================================
ERROR: test_badbytes (testcases.test_general.GeneralTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/ropper/testcases/test_general.py", line 49, in setUp
    self.rs.loadGadgetsFor()
  File "/private/tmp/ropper/ropper/service.py", line 648, in loadGadgetsFor
    load_gadgets(fc)
  File "/private/tmp/ropper/ropper/service.py", line 637, in load_gadgets
    f.allGadgets = self.__ropper.searchGadgets(f.loader, instructionCount=self.options.inst_count, gtype=gtype,multiprocessing=self.options.multiprocessing)
  File "/private/tmp/ropper/ropper/rop.py", line 290, in searchGadgets
    mp.set_start_method('fork')
  File "/nix/store/smzcb4angbhnb8zal91bfhxhaj0iwpxg-python3-3.9.13/lib/python3.9/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

======================================================================
ERROR: test_opcode_failures (testcases.test_general.GeneralTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/ropper/testcases/test_general.py", line 49, in setUp
    self.rs.loadGadgetsFor()
  File "/private/tmp/ropper/ropper/service.py", line 648, in loadGadgetsFor
    load_gadgets(fc)
  File "/private/tmp/ropper/ropper/service.py", line 637, in load_gadgets
    f.allGadgets = self.__ropper.searchGadgets(f.loader, instructionCount=self.options.inst_count, gtype=gtype,multiprocessing=self.options.multiprocessing)
  File "/private/tmp/ropper/ropper/rop.py", line 290, in searchGadgets
    mp.set_start_method('fork')
  File "/nix/store/smzcb4angbhnb8zal91bfhxhaj0iwpxg-python3-3.9.13/lib/python3.9/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

======================================================================
ERROR: test_search (testcases.test_general.GeneralTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/ropper/testcases/test_general.py", line 49, in setUp
    self.rs.loadGadgetsFor()
  File "/private/tmp/ropper/ropper/service.py", line 648, in loadGadgetsFor
    load_gadgets(fc)
  File "/private/tmp/ropper/ropper/service.py", line 637, in load_gadgets
    f.allGadgets = self.__ropper.searchGadgets(f.loader, instructionCount=self.options.inst_count, gtype=gtype,multiprocessing=self.options.multiprocessing)
  File "/private/tmp/ropper/ropper/rop.py", line 290, in searchGadgets
    mp.set_start_method('fork')
  File "/nix/store/smzcb4angbhnb8zal91bfhxhaj0iwpxg-python3-3.9.13/lib/python3.9/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

----------------------------------------------------------------------
Ran 31 tests in 3.917s

FAILED (errors=3)
```

I've also tested this with a prerelease version of Python (Python 3.11.0a7) and I have the same result.

**Comment by sashs** [comment]
Thank you for reporting that, I will look at this

**Comment by sashs** [comment]
Bug is fixed in the new version
