### ISSUE TITLE
Error trying to get some gadgets on libc

### ISSUE THREAD

**Issue by Grimmjsp** [sashs/Ropper#161]
Stacktrace:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ropper/__init__.py", line 52, in start
    Console(app_options).start()
  File "/usr/lib/python3.10/site-packages/ropper/console.py", line 184, in start
    self.__loadFile(file)
  File "/usr/lib/python3.10/site-packages/ropper/console.py", line 202, in __loadFile
    self.__rs.addFile(file, raw=self.__options.raw,
  File "/usr/lib/python3.10/site-packages/ropper/service.py", line 526, in addFile
    loader = Loader.open(name, bytes=bytes, raw=raw, arch=arch)
  File "/usr/lib/python3.10/site-packages/ropper/loaders/loader.py", line 188, in open
    raise ArgumentError('Architecture has to be set, if raw file should be loaded')
ropper.common.error.ArgumentError: Architecture has to be set, if raw file should be loaded

**Comment by sashs** [comment]
Hi, 

could you share the binary, please?
