### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_start_method'

### ISSUE THREAD

**Issue by gmorenope** [sashs/Ropper#165]
Hi.

When I try to open a file I get the following error.

(ropper)> **file libc-2.28.so**
[INFO] Load gadgets for section: LOAD
[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 62, in cmd
    func(self, text)
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 649, in do_file
    self.__loadFile(text)
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 211, in __loadFile
    self.__loadGadgets()
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 302, in __loadGadgets
    self.__searchGadgetsFor(self.currentFileName)
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 306, in __searchGadgetsFor
    self.__rs.loadGadgetsFor(binary)
  File "/usr/local/lib/python2.7/dist-packages/ropper/service.py", line 652, in loadGadgetsFor
    load_gadgets(fc)
  File "/usr/local/lib/python2.7/dist-packages/ropper/service.py", line 637, in load_gadgets
    f.allGadgets = self.__ropper.searchGadgets(f.loader, instructionCount=self.options.inst_count, gtype=gtype,multiprocessing=self.options.multiprocessing)
  File "/usr/local/lib/python2.7/dist-packages/ropper/rop.py", line 289, in searchGadgets
    if mp.get_start_method() != 'fork':
AttributeError: 'module' object has no attribute 'get_start_method'

![ropper](https://user-images.githubusercontent.com/40058699/209987128-1e8aa9e0-8cf5-41e9-8751-c810e2561520.jpg)

Thanks in advance!

**Comment by sashs** [comment]
Hi,

since python2 is eol and there are no new updates for python2 since 2020, python2 is not supported anymore by ropper. You need to use python3.

**Comment by gmorenope** [comment]
>OK, thank you!
