### ISSUE TITLE
loading libc error

### ISSUE THREAD

**Issue by ghalwash** [sashs/Ropper#167]
(ropper)> file libc-2.27.so
[INFO] Load gadgets for section: LOAD
[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/home/haitham/.local/lib/python2.7/site-packages/ropper/console.py", line 62, in cmd
    func(self, text)
  File "/home/haitham/.local/lib/python2.7/site-packages/ropper/console.py", line 649, in do_file
    self.__loadFile(text)
  File "/home/haitham/.local/lib/python2.7/site-packages/ropper/console.py", line 211, in __loadFile
    self.__loadGadgets()
  File "/home/haitham/.local/lib/python2.7/site-packages/ropper/console.py", line 302, in __loadGadgets
    self.__searchGadgetsFor(self.currentFileName)
  File "/home/haitham/.local/lib/python2.7/site-packages/ropper/console.py", line 306, in __searchGadgetsFor
    self.__rs.loadGadgetsFor(binary)
  File "/home/haitham/.local/lib/python2.7/site-packages/ropper/service.py", line 652, in loadGadgetsFor
    load_gadgets(fc)
  File "/home/haitham/.local/lib/python2.7/site-packages/ropper/service.py", line 637, in load_gadgets
    f.allGadgets = self.__ropper.searchGadgets(f.loader, instructionCount=self.options.inst_count, gtype=gtype,multiprocessing=self.options.multiprocessing)
  File "/home/haitham/.local/lib/python2.7/site-packages/ropper/rop.py", line 289, in searchGadgets
    if mp.get_start_method() != 'fork':
AttributeError: 'module' object has no attribute 'get_start_method'

**Comment by sashs** [comment]
Hi. 
The reason is that you use python 2.7. Python 2.7 is not supported anymore.
