### ISSUE TITLE
Ubuntu install of ropper fails. NameError: name 'CS_ARCH_ARM64' is not defined. Did you mean: ' CS_ARCH_ARM'

### ISSUE THREAD

**Issue by csergi** [sashs/Ropper#185]
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/__init__.py", line 29, in <module>
    from .console import Console
  File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/console.py", line 29, in <module>
    from ropper.loaders.loader import Loader, Type
  File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/loaders/__init__.py", line 29, in <module>
    from . import elf
  File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/loaders/elf.py", line 30, in <module>
    from ropper.loaders.loader import *
  File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/loaders/loader.py", line 33, in <module>
    from ropper.arch import *
  File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/arch.py", line 535, in <module>
    ARM64 = ArchitectureArm64()
            ^^^^^^^^^^^^^^^^^^^
  File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/common/abstract.py", line 41, in __call__
    self._instance = super(AbstractSingletonMeta, self).__call__()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/arch.py", line 441, in __init__
    super(ArchitectureArm64, self).__init__(CS_ARCH_ARM64, CS_MODE_ARM, 8, 4)
                                            ^^^^^^^^^^^^^
NameError: name 'CS_ARCH_ARM64' is not defined. Did you mean: 'CS_ARCH_ARM'?

Fresh install, ropper 1.13.8

**Comment by sashs** [comment]
Many thanks. 
Capstone has renamed a global variable. I am fixing this in the bugfix branch

**Comment by GUANZH1** [comment]
> Traceback (most recent call last): File "", line 189, in _run_module_as_main File "", line 148, in _get_module_details File "", line 112, in _get_module_details File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/**init**.py", line 29, in from .console import Console File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/console.py", line 29, in from ropper.loaders.loader import Loader, Type File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/loaders/**init**.py", line 29, in from . import elf File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/loaders/elf.py", line 30, in from ropper.loaders.loader import * File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/loaders/loader.py", line 33, in from ropper.arch import * File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/arch.py", line 535, in ARM64 = ArchitectureArm64() ^^^^^^^^^^^^^^^^^^^ File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/common/abstract.py", line 41, in **call** self._instance = super(AbstractSingletonMeta, self).**call**() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/astracerus/.local/lib/python3.12/site-packages/ropper/arch.py", line 441, in **init** super(ArchitectureArm64, self).**init**(CS_ARCH_ARM64, CS_MODE_ARM, 8, 4) ^^^^^^^^^^^^^ NameError: name 'CS_ARCH_ARM64' is not defined. Did you mean: 'CS_ARCH_ARM'?
> 
> Fresh install, ropper 1.13.8

I tried to install capstone == 5.0.0 , and succeed . I guess maybe low version capstone library didn't rename this global variable

**Comment by GUANZH1** [comment]
And I wanntd to konw , where is the setup.py

> Many thanks. Capstone has renamed a global variable. I am fixing this in the bugfix branch

**Comment by Naupjjin** [comment]
My solution is use `pip3 install --user 'capstone<6'`
Maybe you need to check your capstone version.

**Comment by sashs** [comment]
Should work now with all capstone versions.

**Comment by sashs** [comment]
@GUANZH1 
setup.py is replaced with pyproject.toml
In order to install ropper plz use `pip install .`
