### ISSUE TITLE
Make install_requires meaningful.

### ISSUE THREAD

**Issue by NoviceLive** [sashs/Ropper#20]
# Description
Since you exported many symbols in ``ropper/__init__.py`` and also kept ``VERSION`` in it, ``import ropper`` in ``setup.py`` will fail when the user does not installed ``capstone`` and ``filebytes``, which means ``install_requires`` is of no use and every user has to install them manually.

Simply speaking, ``pip install ropper`` or ``python setup.py install`` will never work unless the user has manually installed ``capstone`` and ``filebytes``, which is, as a matter of fact, inconvenient.
# Sample Output
```
$ pip freeze                                                                                                                         :(
$ pip install ropper
Collecting ropper
  Using cached ropper-1.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z6hx5_9l/ropper/setup.py", line 2, in <module>
        import ropper
      File "/tmp/pip-build-z6hx5_9l/ropper/ropper/__init__.py", line 20, in <module>
        from .console import Console
      File "/tmp/pip-build-z6hx5_9l/ropper/ropper/console.py", line 20, in <module>
        from ropper.loaders.loader import Loader,Type
      File "/tmp/pip-build-z6hx5_9l/ropper/ropper/loaders/__init__.py", line 20, in <module>
        from . import elf
      File "/tmp/pip-build-z6hx5_9l/ropper/ropper/loaders/elf.py", line 21, in <module>
        from ropper.loaders.loader import *
      File "/tmp/pip-build-z6hx5_9l/ropper/ropper/loaders/loader.py", line 24, in <module>
        from ropper.arch import *
      File "/tmp/pip-build-z6hx5_9l/ropper/ropper/arch.py", line 26, in <module>
        from capstone import *
    ImportError: No module named 'capstone'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z6hx5_9l/ropper/
```

**Comment by sashs** [comment]
Yes, you are right. Since I have installed all needed libraries, I have never seen that. I will change that. Thank you.

**Comment by NoviceLive** [comment]
My pleasure. You might want to see how [scrapy](https://github.com/scrapy/scrapy/blob/master/scrapy/__init__.py) handle this.

**Comment by sashs** [comment]
Hey, 
I used a simple workaround. Now there shouldn't be problems. 
The scrapy way doesn't work for me, I have to look for another possibility, but I will do that later.
