### ISSUE TITLE
Ropper tries to work on previously opened path 

### ISSUE THREAD

**Issue by eternaleclipse** [sashs/Ropper#79]
Ropper tries to open a previously opened path, if currently passed filename and previously opened filename are the same.

Steps to reproduce:
```
rm -r ~/.ropper
cp /bin/ls /tmp/myfile
~/Ropper/Ropper.py -f /tmp/myfile --chain execve
mkdir /tmp/a
mv /tmp/myfile /tmp/a/myfile
~/Ropper/Ropper.py -f /tmp/a/myfile --chain execve
```

```
[INFO] Load gadgets from cache
[LOAD] loading... 100%

...

[INFO] syscall opcode not found
[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/home/user/Ropper/ropper/console.py", line 53, in cmd
    func(self, text)
  File "/home/user/Ropper/ropper/console.py", line 485, in __handleOptions
    self.__generateChain(options.chain)
  File "/home/user/Ropper/ropper/console.py", line 363, in __generateChain
    raise e
KeyError: '/tmp/myfile'
```

The reason for this probably has to do with the way the cache is handled in ```~/.ropper/cache```.

**Comment by sashs** [comment]
Should be fixed in the dev branch. Filename is replaced with checksum.
