### ISSUE TITLE
NameError: global name 'regs' is not defined

### ISSUE THREAD

**Issue by baymax0day** [sashs/Ropper#85]
[ERROR] Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/ropper/console.py", line 53, in cmd
    func(self, text)
  File "build/bdist.linux-x86_64/egg/ropper/console.py", line 485, in __handleOptions
    self.__generateChain(options.chain)
  File "build/bdist.linux-x86_64/egg/ropper/console.py", line 363, in __generateChain
    raise e
NameError: global name 'regs' is not defined

**Comment by baymax0day** [comment]
OK,
Thanks! :)
