### ISSUE TITLE
Cache save error

### ISSUE THREAD

**Issue by DhavalKapil** [sashs/Ropper#86]
While saving cache, if there is an exception thrown while making directory (https://github.com/sashs/Ropper/blob/4a3ab26900262a2d8582f6e954a19a20d2ff9200/ropper/service.py#L316), `cache_file` variable is `undefined` and is used later (https://github.com/sashs/Ropper/blob/4a3ab26900262a2d8582f6e954a19a20d2ff9200/ropper/service.py#L342).

```
[Errno 13] Permission denied: '/home/user/.ropper'
[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 53, in cmd
    func(self, text)
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 487, in __handleOptions
    self.__loadGadgets()
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 287, in __loadGadgets
    self.__searchGadgetsFor(self.currentFileName)
  File "/usr/local/lib/python2.7/dist-packages/ropper/console.py", line 291, in __searchGadgetsFor
    self.__rs.loadGadgetsFor(binary)
  File "/usr/local/lib/python2.7/dist-packages/ropper/service.py", line 621, in loadGadgetsFor
    load_gadgets(fc)
  File "/usr/local/lib/python2.7/dist-packages/ropper/service.py", line 609, in load_gadgets
    self.__saveCache(f)
  File "/usr/local/lib/python2.7/dist-packages/ropper/service.py", line 342, in __saveCache
    if os.path.exists(cache_file+'_%d' % i):
UnboundLocalError: local variable 'cache_file' referenced before assignment
```

**Comment by sashs** [comment]
Thank you.
is the directory not writable?
