### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Kaka201** [sashs/Ropper#95]
when i use this commend : `ropper -f vmlinux --search "iretq"`

[INFO] Load gadgets for section: LOAD
[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/ropper/console.py", line 62, in cmd
    func(self, text)
  File "build/bdist.linux-x86_64/egg/ropper/console.py", line 501, in __handleOptions
    self.__loadGadgets()
  File "build/bdist.linux-x86_64/egg/ropper/console.py", line 299, in __loadGadgets
    self.__searchGadgetsFor(self.currentFileName)
  File "build/bdist.linux-x86_64/egg/ropper/console.py", line 303, in __searchGadgetsFor
    self.__rs.loadGadgetsFor(binary)
  File "build/bdist.linux-x86_64/egg/ropper/service.py", line 631, in loadGadgetsFor
    load_gadgets(fc)
  File "build/bdist.linux-x86_64/egg/ropper/service.py", line 616, in load_gadgets
    f.allGadgets = self.__ropper.searchGadgets(f.loader, instructionCount=self.options.inst_count, gtype=gtype)
  File "build/bdist.linux-x86_64/egg/ropper/rop.py", line 286, in searchGadgets
    newGadgets = self._searchGadgetsForked(section=section, binary=binary, instruction_count=instructionCount, gtype=gtype)
  File "build/bdist.linux-x86_64/egg/ropper/rop.py", line 370, in _searchGadgetsForked
    processes[cpu].start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by Kaka201** [comment]
Sorry, I know how to solve it. If you compile and install capstone, you can solve this problem.
