### ISSUE TITLE
Ropper fails on a kernel module

### ISSUE THREAD

**Issue by disconnect3d** [sashs/Ropper#96]
TLDR: Ropper fails to work on an ELF which is also a kernel module.

```
dc@ubuntu:~/train/snote_pwn/snote$ ropper -f ./snote.ko 
[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/home/dc/.local/lib/python2.7/site-packages/ropper/console.py", line 53, in cmd
    func(self, text)
  File "/home/dc/.local/lib/python2.7/site-packages/ropper/console.py", line 492, in __handleOptions
    self.__loadGadgets()
  File "/home/dc/.local/lib/python2.7/site-packages/ropper/console.py", line 290, in __loadGadgets
    self.__searchGadgetsFor(self.currentFileName)
  File "/home/dc/.local/lib/python2.7/site-packages/ropper/console.py", line 294, in __searchGadgetsFor
    self.__rs.loadGadgetsFor(binary)
  File "/home/dc/.local/lib/python2.7/site-packages/ropper/service.py", line 622, in loadGadgetsFor
    load_gadgets(fc)
  File "/home/dc/.local/lib/python2.7/site-packages/ropper/service.py", line 595, in load_gadgets
    Gadget.IMAGE_BASES[f.loader.checksum] = f.loader.imageBase
  File "/home/dc/.local/lib/python2.7/site-packages/ropper/loaders/loader.py", line 138, in imageBase
    return self._getImageBase()
  File "/home/dc/.local/lib/python2.7/site-packages/ropper/loaders/elf.py", line 44, in _getImageBase
    return self._binary.imageBase
  File "/home/dc/.local/lib/python2.7/site-packages/filebytes/elf.py", line 869, in imageBase
    return self.segments[0].header.p_vaddr - self.segments[0].header.p_offset
IndexError: list index out of range
```

Here is the module with changed extension, please remove the `.zip`:
[snote.ko.zip](https://github.com/sashs/Ropper/files/3049023/snote.ko.zip)

**Comment by sashs** [comment]
This bug refers to the file parser (filebytes). I will check that.

**Comment by sashs** [comment]
Thx for reporting.

**Comment by sashs** [comment]
I pushed a fix for ropper and filebytes.

**Comment by disconnect3d** [comment]
thx!
